#!/bin/bash

##################################################
#
#	Replace the following value with the 
#	UUID for your connection.
#
##################################################
CON_UUID='ec85e76c-5f9e-46ec-ba7b-44c407d4e1b0'
VPNCON=$(nmcli con status uuid $CON_UUID | grep  "GENERAL.STATE:" | cut  -d":" -f2 | tr -d ' ')
if [[ $VPNCON != 'activated' ]]; then
	echo "Disconnected, trying to reconnect..."
	(sleep 1s && nmcli con up uuid $con_uuid)
else
	echo "Already connected !"
fi
