#!/bin/bash

##################################################
#
#	Replace the following value with the 
#	UUID for your connection.
#
##################################################
CON_UUID='YOURUUIDHERE'
VPNCON=$(nmcli con status uuid $CON_UUID | grep  "GENERAL.STATE:" | cut  -d":" -f2 | tr -d ' ')
if [[ $VPNCON != 'activated' ]]; then
	echo "Disconnected, trying to reconnect..."
	(sleep 1s && nmcli con up uuid $con_uuid)
else
	echo "Already connected !"
fi
